// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgXkQroiaUMhIJ4iMeEBhG_yXcx10vtuw',
    appId: '1:852083201556:web:67eb3681dbabc3679ff901',
    messagingSenderId: '852083201556',
    projectId: 'rest-4ad5e',
    authDomain: 'rest-4ad5e.firebaseapp.com',
    storageBucket: 'rest-4ad5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT824EbVQ-IdIrQ3e059J4wljfJeAmIos',
    appId: '1:852083201556:android:5351efc0a05a50739ff901',
    messagingSenderId: '852083201556',
    projectId: 'rest-4ad5e',
    storageBucket: 'rest-4ad5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnYNYQBiCE_Ufh5K5rELInjl15MB913A',
    appId: '1:852083201556:ios:291293a705390f199ff901',
    messagingSenderId: '852083201556',
    projectId: 'rest-4ad5e',
    storageBucket: 'rest-4ad5e.firebasestorage.app',
    iosBundleId: 'com.example.learning210c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxnYNYQBiCE_Ufh5K5rELInjl15MB913A',
    appId: '1:852083201556:ios:291293a705390f199ff901',
    messagingSenderId: '852083201556',
    projectId: 'rest-4ad5e',
    storageBucket: 'rest-4ad5e.firebasestorage.app',
    iosBundleId: 'com.example.learning210c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgXkQroiaUMhIJ4iMeEBhG_yXcx10vtuw',
    appId: '1:852083201556:web:ec81f02be17c78659ff901',
    messagingSenderId: '852083201556',
    projectId: 'rest-4ad5e',
    authDomain: 'rest-4ad5e.firebaseapp.com',
    storageBucket: 'rest-4ad5e.firebasestorage.app',
  );
}
