// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd0OLwWKRDGPXN_eSZmDV_nDLZCZbjLl0',
    appId: '1:409801412024:web:1d1afb4c1a97f9df49934d',
    messagingSenderId: '409801412024',
    projectId: 'restaurante-yds',
    authDomain: 'restaurante-yds.firebaseapp.com',
    storageBucket: 'restaurante-yds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9VEDHnelCjvjP36YuHL2hNlCBX2K6iiw',
    appId: '1:409801412024:android:7c8b21261a22575f49934d',
    messagingSenderId: '409801412024',
    projectId: 'restaurante-yds',
    storageBucket: 'restaurante-yds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk4B2B6eePAFptsCjOMBEqFcllPZ-I-s4',
    appId: '1:409801412024:ios:2bf0099521e4ac1c49934d',
    messagingSenderId: '409801412024',
    projectId: 'restaurante-yds',
    storageBucket: 'restaurante-yds.firebasestorage.app',
    iosBundleId: 'com.example.learning210c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk4B2B6eePAFptsCjOMBEqFcllPZ-I-s4',
    appId: '1:409801412024:ios:2bf0099521e4ac1c49934d',
    messagingSenderId: '409801412024',
    projectId: 'restaurante-yds',
    storageBucket: 'restaurante-yds.firebasestorage.app',
    iosBundleId: 'com.example.learning210c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd0OLwWKRDGPXN_eSZmDV_nDLZCZbjLl0',
    appId: '1:409801412024:web:1fe132871c5e23d749934d',
    messagingSenderId: '409801412024',
    projectId: 'restaurante-yds',
    authDomain: 'restaurante-yds.firebaseapp.com',
    storageBucket: 'restaurante-yds.firebasestorage.app',
  );
}
